CanalTP/artemis

artemis/tests/mission_test.py

jira: http://jira.canaltp.fr/browse/ITI-204

activate tests

---

artemis/test_mechanism.py

fix test fixture

---

artemis/tests/map_test.py

xfail deleted in all the test on map_test

artemis: xfail deleted in all the tests

---

artemis/test_mechanism.py

Remove some log, but mostly add db mandatory value

following PR https://github.com/CanalTP/navitia/pull/1883

---

artemis/tests/auvergne_test.py

need https://github.com/CanalTP/navitia/pull/1886

add a test for the admin to admin

---

artemis/tests/bibus_test.py
artemis/tests/destineo_test.py

to check geodata sources and numbers of geo objects

add test on _geo_status

---

artemis/tests/guichet_unique_test.py
artemis/tests/rebroussement_test.py
artemis/tests/saintomer_tad_test.py
artemis/tests/sherbrooke_test.py

needs https://github.com/CanalTP/artemis_references/pull/83 to be merged synchronously

Fix experimental scenario

---

artemis/tests/bibus_test.py
artemis/tests/itl_test.py
artemis/tests/sherbrooke_test.py

concerned ticket: http://jira.canaltp.fr/browse/ITI-212

artemis: xfail deleted as these test results are XPASS

---

artemis/default_checker.py
artemis/tests/bibus_test.py

6 tests on error added for bibus.
Concerned Ticket: http://jira.canaltp.fr/browse/ITI-343
Attention: Only those 6 tests added will fail but not others

artemis: we test also error messages

---

artemis/tests/bibus_test.py

Last PR for http://jira.canaltp.fr/browse/ITI-343

artemis: xfail deleted as test results are XPASS

---

artemis/tests/auvergne_test.py
artemis/tests/destineo_test.py
artemis/tests/guichet_unique_test.py
artemis/tests/saintomer_tad_test.py
artemis/tests/tad_test.py

needed after merge of https://github.com/CanalTP/navitia/pull/1927

admin id has changed, so we have to update requests from admins

---

artemis/tests/fixtures/trip_delay_866143.xml
artemis/tests/fixtures/trip_partially_deleted_866143.xml
artemis/tests/guichet_unique_test.py

needs https://github.com/CanalTP/navitia/pull/2061
TODO update reference

add partial delete test

---

artemis/tests/bibus_test.py

https://ci.navitia.io/job/Artemis_nigthly_new_ntfs/479/consoleFull

update artemis bibus test

---

artemis/tests/auvergne_test.py

New tests cover the features :
- free_radius_from
- min_nb_journeys
- no_shared_section

Add tests for latest navitia features

---

artemis/test_mechanism.py
artemis/tests/auvergne_test.py

References updated in : https://github.com/CanalTP/artemis_references/pull/133

Add timeframe_duration tests

---

artemis/base_pytest.py

New_Artemis : Add APIs for Kirin

---

artemis/base_pytest.py
artemis/utils.py

https://github.com/CanalTP/artemis/commit/eee3fa55b32b3960aba13c16e38b2f9872397262#diff-5bd56206d31e817e3dd3c6af0850e073L275

fix artemis assert

---

artemis/tests/fixtures/trip_seq1_02_delays_with_last_back_to_normal.json
artemis/tests/guichet_unique_test.py

Artemis reference PR : https://github.com/CanalTP/artemis_references/pull/156
Jenkins : https://ci.navitia.io/job/custom_artemis_reference_branch_and_artemis_branch_build/201/

[FIRST] SNCF test sequence 1

---

artemis/tests/fixtures/trip_seq3_01_add_new_stop_point.json
artemis/tests/fixtures/trip_seq3_02_add_delay.json
artemis/tests/fixtures/trip_seq3_03_back_to_normal.json
artemis/tests/fixtures/trip_seq3_04_add_delay.json
artemis/tests/fixtures/trip_seq5_01_remove_stops.json
artemis/tests/fixtures/trip_seq5_02_add_stop.json
artemis/tests/fixtures/trip_seq5_03_back_to_normal.json
artemis/tests/guichet_unique_test.py

Corresponding references: https://github.com/CanalTP/artemis_references/pull/155

[FIRST] SNCF test sequence 3 & 5

---

artemis/readme.md

TODO:
:warning: change your artemis config if you use that already

Document change of port in navitia-docker-compose

---

artemis/tests/fixtures/trip_seq9_01_delays_and_new_stop_points.json
artemis/tests/fixtures/trip_seq9_02_update_delays.json
artemis/tests/fixtures/trip_seq9_03_delays_and_delete_stop_points.json
artemis/tests/guichet_unique_test.py

_JIRA_ :  https://jira.kisio.org/browse/NAVP-1153.
Before merging, please have a look of https://github.com/CanalTP/artemis_references/pull/159 and merge it.

Cots test seq 09

---

artemis/tests/fixtures/trip_seq9_01_delays_and_new_stop_points.json
artemis/tests/fixtures/trip_seq9_02_update_delays.json
artemis/tests/fixtures/trip_seq9_03_delays_and_delete_stop_points.json
artemis/tests/guichet_unique_test.py

Ticket jira: https://jira.kisio.org/browse/NAVP-1153
Merged PR: https://github.com/CanalTP/artemis/pull/298

artemis: Modifications on previous PR of Cots test seq 09

---

artemis/tests/fixtures/trip_add_new_trip_151515.json
artemis/tests/fixtures/trip_remove_new_trip_151515.json
artemis/tests/guichet_unique_test.py

https://jira.kisio.org/browse/NAVP-1155

Added trip tests as xfails

---

artemis/default_checker.py

Revert "add taxi in marshaller"

---

artemis/tests/bibus_test.py

After https://github.com/CanalTP/artemis_references/pull/169#discussion_r284321218 ,
This should solve the problem.

Use coords instead of POI id, as it can change

---

artemis/tests/fixtures/trip_add_several_new_stop_points_in_one_cots_9580_tgv.json
artemis/tests/fixtures/trip_seq8_02_detour_start_delay_25_and_add_middle.json
artemis/tests/fixtures/trip_seq8_03_detour_start_delay_40_and_add_middle.json

After https://github.com/CanalTP/kirin/pull/240 , some feeds were broken.

Fix "rang" in COTS feeds

---

artemis/base_pytest.py
artemis/conftest.py
artemis/default_settings.py
requirements.txt

https://jira.kisio.org/browse/NAVP-1093

Add lock for cities

---

artemis/tests/auvergne_test.py

Related to this PR: https://github.com/CanalTP/navitia/pull/2813
Before:
After:

add projection test

---

artemis/base_pytest.py
artemis/docker_orchestrator.py
artemis/tests/auvergne_test.py

https://jira.kisio.org/browse/NAVP-1383
:warning: You know it but still... This is an other step in a big evolution, comments welcome if you can understand the full scope of the evolution.  Please refrain your urge to put comments everywhere. :warning: 
**Main evolution:** Use docopt to run the script "docker_orchestrator". The options and arguments of the script may/will evolve. TBD in a future refinement maybe, for those interested!

[ArtemisNG] Use docopt + improvements

---

artemis/tests/auvergne_test.py

Tests with Asgard doesn't work with ArtemisOld...

Remove Asgard tests

---

artemis/base_pytest.py
artemis/test_mechanism.py
artemis/tests/auvergne_test.py

navitia PR : https://github.com/CanalTP/navitia/pull/2939
references PR : https://github.com/CanalTP/artemis_references/pull/185

Adding tests for direct_path_mode

---

.mergify.yml

mergify doesn't like uppercase in team name :(

fix mergify

---

artemis/conftest.py
artemis/pytest_report_makers.py
requirements.txt

A readable failure report will be very helpful!
https://gist.github.com/xlqian/32c4d5b4b0459f9c8a1c2c81c7eb0169

pytest failure report

---

artemis/pytest_report_makers.py
artemis/tests/auvergne_test.py

https://github.com/CanalTP/navitia/pull/3002
ref: https://github.com/CanalTP/artemis_references/compare/add_test_direct_path_with_non_default_speed?expand=1

add test and minor fix in failure report

---

artemis/pytest_report_makers.py
artemis/tests/auvergne_test.py

Revert "add test and minor fix in failure report"

---

artemis/base_pytest.py
artemis/tests/bibus_test.py
artemis/utils.py

https://jira.kisio.org/browse/NAVP-1440
- Allow to make requests with no coverage
- Use checker according to request, not always default journeys checker
- Utils function compatible py2/py3
- Add check before updating instance db values

[ArtemisNG] Various improvements

---

artemis/base_pytest.py
artemis/docker_orchestrator.py

see function `wait_for_instance_configuration()`

[ArtemisNG] Docker orchestrator better synchronization

---

artemis/tests/auvergne_test.py

https://github.com/CanalTP/artemis_references/pull/196

add test direct path with non default speed

---

artemis/base_pytest.py
artemis/default_checker.py
artemis/utils.py

- This PR is bloked by https://github.com/CanalTP/navitia/pull/2982
-  To be merged after:
For details on elements added in response, please see:  https://jira.kisio.org/browse/NAVP-1324

Add tickets in response artemis

---

artemis/base_pytest.py
artemis/tests/idfm_test.py

https://jira.kisio.org/browse/NAVP-1482
With this modification, the IDFM waiting timeout can be reduced

[ArtemisNG] Monitor state of dataset during binarization

---

artemis/readme.md

[ArtemisNG] Improve doc

---

artemis/__init__.py
artemis/docker_orchestrator.py

https://jira.kisio.org/browse/NAVP-1136
With this option, NG will be run nightly in our CI

[NG]  Add option to pull up-to-date Docker images

---

artemis/docker_orchestrator.py

In case the coverage passed as a parameter isn't in the available coverages list

[ArtemisNG] Better errors handling

---

.pre-commit-config.yaml
artemis/base_pytest.py
artemis/docker_orchestrator.py
artemis/readme.md
artemis/test_mechanism.py
pytest.ini

See commit for each improvement

Various improvements

---

artemis/base_pytest.py
artemis/default_checker.py
artemis/test_mechanism.py
artemis/tests/guichet_unique_test.py

Add disruptions in filtered response

---

artemis/base_pytest.py
artemis/default_checker.py
artemis/test_mechanism.py
artemis/tests/guichet_unique_test.py

Revert "Add disruptions in filtered response"

---

artemis/base_pytest.py
artemis/default_checker.py
artemis/test_mechanism.py
artemis/tests/guichet_unique_test.py

https://jira.kisio.org/browse/NAVP-1548
- Full run on Artemis PASSED

Add disruptions in response

---

artemis/tests/auvergne_test.py

https://github.com/CanalTP/navitia/pull/3228
https://ci.navitia.io/view/artemis/job/custom_artemis_reference_branch_and_artemis_branch_build/372/

add_car_park_n_ride_test

---

artemis/base_pytest.py
artemis/pytest_report_makers.py
requirements.txt

[WIP]
[Jira ticket](https://jira.kisio.org/browse/NAVP-1523)
Added diff on places and geo_status in the failures_report file, which is now in html instead of markdown.

[NG] places and geo_status diff in failures report

---

.dockerignore
.gitmodules
Dockerfile
Jenkinsfile
Makefile
artemis/base_pytest.py
artemis/common_fixture.py
artemis/conftest.py
artemis/default_settings.py
artemis/tests/bibus_test.py
artemis/tests/guichet_unique_test.py
artemis/tests/idfm_test.py
artemis/utils.py

This aims at integrating Artemis into our new CI.
* [Jenkins-Core](https://jenkins-core.canaltp.fr/blue/organizations/jenkins/Artemis/activity)
The changes are introducing a few things:
- Adds submodules for the dependencies:
- artemis_references
- artemis_data
- navitia_docker_compose
- Uses a makefile to simplify things and wrap docker-compose commands. You only have to run `make test` to trigger the docker-compose and the tests. 
Available commands are: 
- `make start`                          Deploy Navitia stack and Artemis instances using navitia-docker-compose
- `make test`                           Run Artemis tests
- `make build`                          Build Artemis docker image
- `make pull`                           Pull container images
- `make stop` …

[CI] Jenkins ng

---

artemis/tests/idfm_test.py

Renaming `stif` comment to `idfm` to avoid confusion

Remove references to stif in favor of idfm

---

Jenkinsfile

Update jenkinsfile to add the option to run artemis on a navitia pull_request.
Needs :

Jenkinsfile allows for launch on pull_request

---

Jenkinsfile_artemis_old

To launch artemis on the artemis platform (old-school style) from Jenkins2

Jenkinsfile for old artemis

---

Jenkinsfile_artemis_old

artifacts are retreived in the `post` section

Remove useless step in Jenkinsfile_artemis_old

---

Jenkinsfile

Just added a slack message to poke team

[jenkins] Artemis old crash is not silent

---

Jenkinsfile
Jenkinsfile_artemis_old

Wait for this [PR](https://github.com/CanalTP/jenkins_conf/pull/140) to be merge before merging this one !

Enable console color for Artemis pipelines

---

artemis/pytest_report_makers.py

Write data in report_distribution.csv when creating the file, not only the headers.

[NG] Fix report_distribution.csv

---

Jenkinsfile

Add ssh key and trim commit message

Fix for Artemis NG

---

artemis/base_pytest.py
requirements.txt

Upgrade deepdiff -> Fix seg fault in artemis tests

Fix segfault for Artemis-Loki ony 
