artemis/test_mechanism.py
No more after test, so apache2 keeps on running (needed at least for kirin deploy).
=> Kill jormun before test

artemis/test_mechanism.py, artemis/tests/idfm_test.py
idfm takes long time to load data during which test_mechanism request the coverage all the time, the pybreaker will short circuit the request after max nb of fail...
=> make wait_fixed longer for idfm

artemis/common_fixture.py, artemis/test_mechanism.py, artemis/tests/guichet_unique_test.py
Also reactivate test_kirin_cots_trip_add_new_stop_point_in_the_middle that was not chaining well with previous test.
JIRA: https://jira.kisio.org/browse/NAVP-1135
Please have a look at the limitations commented in JIRA
TODO (`do_not_merge` labels that):
=> Clean Kirin db at each test, only for GuichetUnique

artemis/tests/fixtures/trip_base_9580_tgv.json, artemis/tests/fixtures/trip_delay_9580_tgv.json
Until now, COTS in Artemis are wrong.
We have differents errors like: _schedules, stop point list, etc.._
This PR aims to create a `base COTS flow`. You can **derivate** it to develop differents cases.
I did this job, before starting https://jira.kisio.org/browse/NAVP-1099, case 1
In addtion, I updated _trip_delay_9580_tgv.json_ with good params too.
We have new reference because I change delays (10 min) : https://github.com/CanalTP/artemis_references/pull/153
The base COTS is based on the classical 
- 14:01 > 14:01 gare de Frankfurt-am-Main-Hbf
- etc ...
- 21:46 > 21:46 gare de Marseille-St-Charles
=> create new base cots + update delays cots

artemis/tests/fixtures/trip_add_several_new_stop_points_in_one_cots_9580_tgv.json
As delays are now correctly read, this one was inconsistent
TODO:
=> Fix after kirin correction for read of add+delay

artemis/tests/fixtures/trip_add_paris_marseille.json, artemis/tests/fixtures/trip_add_paris_marseille_delete_with_delay_15_and_stop_time_added.json, artemis/tests/fixtures/trip_add_paris_marseille_to_normal.json, artemis/tests/fixtures/trip_add_paris_marseille_with_delay_15.json, artemis/tests/fixtures/trip_add_paris_marseille_with_delay_15_and_stop_time_added.json, artemis/tests/fixtures/trip_add_paris_marseille_with_delay_15_and_stop_time_deleted.json, artemis/tests/guichet_unique_test.py
Tests on trip add with multiple actions:
1. Add a new trip, update with a delay and update to normal
2. Add a new trip, update with a delay, update with a stop_time deleted and update to normal  
3. Add a new trip, update with a delay, update with a new stop_time and delete de trip
For details see: https://jira.kisio.org/browse/NAVP-1068
=> artemis: tests added on trip add chaining with some options

artemis/tests/guichet_unique_test.py
Technical detail:
This will make Kirin send an "UNKNOWN_EFFECT" feed to Kraken.
TODO:
> https://github.com/CanalTP/artemis_references/pull/162
=> Add a test on full back-to-normal feed

artemis/base_pytest.py, artemis/test_mechanism.py, artemis/tests/guichet_unique_test.py
Passed from 25s to 1min.
Also minor unrelated changes (see commit messages).
TODO (`do_not_merge` labels this):
=>  Allow longer RT-reload on artemis

artemis/tests/fixtures/trip_add_paris_marseille_with_delay_15_and_stop_time_deleted.json, artemis/tests/guichet_unique_test.py
Concerns: https://jira.kisio.org/browse/NAVP-1251
TODO:
With kraken reloaded before each test, GuichetUniqueTest takes 9 minutes more then before.(28 minutes instead of 19 minutes)
=> [Cots]: Activate tests on added trip

artemis/common_fixture.py
Adds two contributors : "realtime.sherbrooke" and "realtime.cots" while cleaning the database kirin for each test
Note: Test on "guichet_unique_test" inserts two contributors and all tests are valide
=> artemis: init two contributors

artemis/common_fixture.py
It happens that our CI fails on cleaning Kirin's DB. 
To help trouble shoot the issue, we need more information on the matter.
=> Print out explicit exception on clean_kirin_db error

artemis/base_pytest.py, artemis/conftest.py, artemis/tests/idfm_test.py
Instead of waiting a loooong time for Kraken to restart, ArtemisNG now monitors Tyr jobs to check how is the binarization going.
https://jira.kisio.org/browse/NAVP-1415
Next step to complete this PR:
Have only one dataset by job for a better monitoring and a better future on the NG planet.
https://jira.kisio.org/browse/NAVP-1466
**Side quests**:
- query cities db status less often
- remove unused data type 'poi' because there's no folder 'poi' in artemis_data
- longer timeout for IdfM binarization (fusio2ed can last >10min)
=> [ArtemisNG] Monitor Tyr jobs during binarization

artemis/utils.py
Fix artemis NG (python3.7) warning: `DeprecationWarning: The import 'werkzeug.url_fix' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.urls import url_fix' instead.`
=> Update import of url_fix

artemis/base_pytest.py
- Wait for Kraken reload using instance timeout: useful for IdfM
- Take into account '.csv' files for binarization: needed to have tickets in response
=> [ArtemisNG] Improvements

artemis/tests/airport01_test.py, artemis/tests/airport_test.py
All tests from coverages "airport" and "airport-01" used to be xfail, but they are actually passing.
So, let's run them!
https://ci.navitia.io/view/custom_artemis/job/custom_artemis_reference_branch_and_artemis_branch_build/304/console
It was related to: https://jira.kisio.org/browse/NAVP-47 that is now closed
=> Un-xfail airport tests

artemis/base_pytest.py, artemis/common_fixture.py, artemis/test_mechanism.py
Add log about time spent between sending the COTS feed and Kraken reloading:
```
[2020-03-19 16:14:49,970] [ INFO] [   artemis.common_fixture] test_kirin_cots_trip_detour_at_the_end: RT processed in 28.8s (Kirin:0.43/Kraken:28.37)
```
=> Add log about RT processing

artemis/default_settings.py, artemis/docker_orchestrator.py
For each coverage run, a log folder is created with every container logs stored in separate files.
etc...
and in the folder:
=> [NG] Option to store container logs

artemis/compose_settings.py, artemis/tests/saintomer_tad_test.py
Several times now that the tests fail due to the timeout for saintomer:
`saintomer: geopal2ed 120.191229492s`
Sidequest:
In order to reduce the command line in Jenkins with env parameters to override, create a file with docker-compose constant params
=> [ArtemisNG] Increase SaintOmer timeout

artemis/tests/prolong_auto_test.py
Here comes the reproduction of a bug that has been found with Ch-leman.
We can see that the journey goes back in time with a negative duration
"duration": -1800
This is due to allowing drop-off and pickup at the extremity of a trips that has a prolongation.
=> [prolong-auto] Add test that demonstrates a prolongation goes back in time

artemis/tests/prolong_auto_test.py, artemis/tests/prolong_mano_test.py
This test that was added in #378 has its data in prolong-auto, which is automatically generated by Fusio.
Because of this, the data couldn't be integrated in fusio and it is since then failling the job artemis_nighly_NTFS.
Needs : 
After the merge
=> [Prolong-mano] Prolong auto to mano

artemis/tests/idfm_test.py
With recent changes in raptor we can remove max_extra_second_pass for IDFM.
* Fix the following tests: 
-- artemis.tests.idfm_test.TestIdfMNewDefault.test_idfm_111
-- artemis.tests.idfm_test.TestIdfMNewDefault.test_idfm_187
-- artemis.tests.idfm_test.TestIdfMExperimental.test_idfm_111
-- artemis.tests.idfm_test.TestIdfMExperimental.test_idfm_187
=> Set extra_max_second_pass to 0 for IDFM

artemis/base_pytest.py
We were waiting for all types of data even though they were not valid. Which was causing the tests to hang before timing out. 
We are now only processing and waiting for valid datasets.
=> [NG] Fix  put_data func for 

artemis/base_pytest.py, artemis/test_mechanism.py, artemis/utils.py
This work takes its roots in Mehdi's PR (#374) in order to by able to easily compare references between Ye Old Artemis with NG. 
This does not change the nature of the response or the reference. It only change the order of which dictionaries are displayed. Dictionaries are sorted by keys in lexical order, but lists are still preserving the same order.
Requirements :
=> Sort Ref responses by keys

Jenkinsfile, Jenkinsfile_artemis_old
We want to send a message if **Artemis Old** fails, not with **Artemis NG** (for the moment)
I got the wrong file `Jenkinsfile ` -> ` Jenkinsfile_artemis_old `
=> [jenkins] wrong artemis with failed messages

Jenkinsfile_artemis_old
Keep the last 30 jobs on the CI for `artemis_old`.
When zipped, artifacts are ~20MB big, thus 600MB max is going to be used to keep a month of history at 1 build a day. Which is plenty if we want to come back to it.
And we save the polar bears at the same time. #BeGreen
=> [CI] Limit artifacts size and jobs on CI

Jenkinsfile
The variable $EVENT was undefined, but using the syntax ${VAR} and sh double quote (sh " ") should fix the issue. 
Tested on a local jenkins.
=> [CI] Fix Jenkins undefined var

artemis/base_pytest.py
Previously, Artemis NG was failling at some tests due to a bad binarization. 
See ticket NAVP-1726 for more details
With this fix, we are now sure to do a full binarization only once for each coverage.
We achieved this goal by suspending tyr_beat docker during the data upload (post) to tyr, then we avoid tyr_beat to run a binarization (ed2nav) for each sub part of the data coverage (osm, fusio, poi...)
=> [CI] Fix Artemis NG

Jenkinsfile, Makefile
We enforce the stop of all artemis containers and removes all images at the very beginning of Jenkins Pipeline, to prevent possible bugs due to zombie containers interacting during the test run.
=> [NG] Improve Artemis NG - Jenkins robustness

artemis/conftest.py
On slow machine ARTEMIS_NG run could fail because of a low timeout for cities_db wait for completion
Before / After
5 min -> 15 min
=> [ARTEMIS_NG] Increase cities_db wait time for completion
